/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Christian
 */
public class frmVeterinarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmVeterinarios
     */
    public frmVeterinarios() {
        initComponents();
        setTitle("Mantenimiento de Veterinarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btnEliminarVeter = new javax.swing.JButton();
        btnBuscarVeter = new javax.swing.JButton();
        lblBuscarNomVeteri = new javax.swing.JLabel();
        txtBuscarVeterinario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVeterinario = new javax.swing.JTable();
        btnRefrescar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblCodProfes = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        txtIdVeteri = new javax.swing.JTextField();
        txtNombreVeteri = new javax.swing.JTextField();
        txtApellido1Veter = new javax.swing.JTextField();
        txtApellido2Veter = new javax.swing.JTextField();
        txtCedulaVeter = new javax.swing.JTextField();
        txtCodProfVeter = new javax.swing.JTextField();
        txtEmailVeter = new javax.swing.JTextField();
        txtTelefonoVeter = new javax.swing.JTextField();
        txtDireccionVeter = new javax.swing.JTextField();
        btnGuardarVeter = new javax.swing.JButton();
        btnLimpiarVeter = new javax.swing.JButton();
        lbActivo = new javax.swing.JLabel();
        cbxActivo = new javax.swing.JCheckBox();
        btnEditarVeter = new javax.swing.JButton();
        lblMantVeterinario = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda:"));

        btnEliminarVeter.setText("Eliminar");
        btnEliminarVeter.setToolTipText("Eliminar Registro en la Base de datos");

        btnBuscarVeter.setText("Buscar");
        btnBuscarVeter.setToolTipText("Buscar información en la Base de Datos");

        lblBuscarNomVeteri.setText("Buscar por Nombre");

        tblVeterinario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVeterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeterinarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVeterinario);

        btnRefrescar.setText("Refrescar");
        btnRefrescar.setToolTipText("Refrescar la busqueda de la Base de datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(lblBuscarNomVeteri, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarVeter))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRefrescar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarVeter)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarVeter)
                    .addComponent(lblBuscarNomVeteri)
                    .addComponent(txtBuscarVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarVeter)
                    .addComponent(btnRefrescar))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos:"));

        lblId.setText("ID:");

        lblNombre.setText("Nombre:");

        lblApellido1.setText("Primer Apellido:");

        lblApellido2.setText("Segundo Apellido:");

        lblCedula.setText("Cedula:");

        lblCodProfes.setText("Codigo Profesional:");

        lblEmail.setText("Email:");

        lblTelefono.setText("Telefono:");

        lblDireccion.setText("Direccion:");

        txtIdVeteri.setEditable(false);

        btnGuardarVeter.setText("Guardar Nuevo");
        btnGuardarVeter.setToolTipText("Guardar Registro");

        btnLimpiarVeter.setText("Limpiar");
        btnLimpiarVeter.setToolTipText("Limpiar Datos");

        lbActivo.setText("Activo");

        btnEditarVeter.setText("Editar");
        btnEditarVeter.setToolTipText("Edita el Registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnGuardarVeter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarVeter)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarVeter))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCodProfes, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreVeteri, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellido1Veter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellido2Veter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCedulaVeter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodProfVeter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefonoVeter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDireccionVeter)
                            .addComponent(cbxActivo, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(txtEmailVeter)
                            .addComponent(txtIdVeteri))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdVeteri)
                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreVeteri)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellido1Veter)
                    .addComponent(lblApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellido2Veter)
                    .addComponent(lblApellido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCedulaVeter)
                    .addComponent(lblCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodProfVeter)
                    .addComponent(lblCodProfes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmailVeter)
                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefonoVeter)
                    .addComponent(lblTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccionVeter)
                    .addComponent(lblDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarVeter)
                    .addComponent(btnLimpiarVeter)
                    .addComponent(btnEditarVeter))
                .addContainerGap())
        );

        lblMantVeterinario.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMantVeterinario.setText("Mantenimiento de Veterinarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMantVeterinario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMantVeterinario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeterinarioMouseClicked
        try {
            int fila = tblVeterinario.getSelectedRow();
            txtIdVeteri.setText(tblVeterinario.getValueAt(fila, 0).toString());
            txtNombreVeteri.setText(tblVeterinario.getValueAt(fila, 1).toString());
            txtApellido1Veter.setText(tblVeterinario.getValueAt(fila, 2).toString());
            txtApellido2Veter.setText(tblVeterinario.getValueAt(fila, 3).toString());
            txtCedulaVeter.setText(tblVeterinario.getValueAt(fila, 4).toString());
            txtCodProfVeter.setText(tblVeterinario.getValueAt(fila, 5).toString());
            txtEmailVeter.setText(tblVeterinario.getValueAt(fila, 6).toString());
            txtTelefonoVeter.setText(tblVeterinario.getValueAt(fila, 7).toString());
            txtDireccionVeter.setText(tblVeterinario.getValueAt(fila, 8).toString());
            int activo = Integer.valueOf(tblVeterinario.getValueAt(fila, 9).toString());
            if (activo != 1) {
                cbxActivo.setSelected(false);
            } else {
                cbxActivo.setSelected(true);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar el registro" + ex.toString());
        }
    }//GEN-LAST:event_tblVeterinarioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarVeter;
    public javax.swing.JButton btnEditarVeter;
    public javax.swing.JButton btnEliminarVeter;
    public javax.swing.JButton btnGuardarVeter;
    public javax.swing.JButton btnLimpiarVeter;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JCheckBox cbxActivo;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbActivo;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblBuscarNomVeteri;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodProfes;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMantVeterinario;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    public javax.swing.JTable tblVeterinario;
    public javax.swing.JTextField txtApellido1Veter;
    public javax.swing.JTextField txtApellido2Veter;
    public javax.swing.JTextField txtBuscarVeterinario;
    public javax.swing.JTextField txtCedulaVeter;
    public javax.swing.JTextField txtCodProfVeter;
    public javax.swing.JTextField txtDireccionVeter;
    public javax.swing.JTextField txtEmailVeter;
    public javax.swing.JTextField txtIdVeteri;
    public javax.swing.JTextField txtNombreVeteri;
    public javax.swing.JTextField txtTelefonoVeter;
    // End of variables declaration//GEN-END:variables
}
